name: turingrk1-kernel

on:
  push:
    branches: [ 'main', 'release-*', 'next-lts' ]
    tags:
      - "v*"
  workflow_dispatch:
env:
  REGISTRY: registry.camsab.me:443
  USER: "talos"

jobs:
  build_kernel:
    runs-on: home-runners

    permissions:
      actions: read
      contents: write
      issues: read
      packages: write
      pull-requests: read

    steps:

      - name: Install make
        run: sudo apt-get update && sudo apt-get install make

      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
              gc = true
              gckeepstorage = 50000

              [[worker.oci.gcpolicy]]
                keepBytes = 10737418240
                keepDuration = 604800
                filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
              [[worker.oci.gcpolicy]]
                all = true
                keepBytes = 53687091200
            [registry."docker-registry.registry.svc.cluster.local:5000"]
              http = true
          driver: kubernetes
          driver-opts: |
            namespace=actions-runner
            replicas=1
            nodeselector=model=rk1
            limits.memory=2G
            limits.ephemeral-storage=2G

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # need history for `git describe` to work for Talos `Makefile`
          fetch-depth: 0
          fetch-tags: true


      - name: Build and push turingrk1 kernel image
        run: make kernel
        env:
          PUSH: '1'
          USERNAME: ${{ github.actor }}
          PLATFORM: linux/arm64
          PROGRESS: plain
          REGISTRY_AND_USERNAME: ${{ env.REGISTRY }}/${{ env.USER }}
          CI_ARGS: "--cache-from=${{ env.REGISTRY }}/${{ env.USER }}/kernel:cache --cache-to=${{ env.REGISTRY }}/${{ env.USER }}/kernel:cache"
